#!/bin/bash

# DEPLOY-RSC-CORS-FIX.sh
# Immediate deployment of CORS + RSC fix for login and dashboard issues

set -e

echo "🚀 DEPLOYING COMPLETE FIX FOR PRODUCTION LOGIN ISSUE"
echo "====================================================="

echo "✅ Docker image built and pushed:"
echo "   limpet/wizardcore-frontend:rsc-cors-fix"
echo ""

echo "📋 Fixes included in this image:"
echo "   1. CORS fix for same-origin requests in auth proxy"
echo "   2. CORS fix for same-origin requests in backend proxy"
echo "   3. Enhanced RSC (React Server Component) detection in middleware"
echo "   4. Proper 401 responses for RSC fetches instead of redirects"
echo "   5. Session refresh awareness in middleware"
echo "   6. Fixed Redis image (redis:7-alpine instead of 7.2-alpine)"
echo ""

echo "🔧 IMMEDIATE DEPLOYMENT COMMANDS:"
echo "----------------------------------"
echo ""
echo "1. Update Docker Compose (already done locally):"
echo "   docker-compose.yml now uses: limpet/wizardcore-frontend:rsc-cors-fix"
echo ""
echo "2. Deploy to production (choose one method):"
echo ""
echo "   Method A: Dokploy Dashboard"
echo "   ---------------------------------"
echo "   - Go to Dokploy Dashboard → WizardCore Application"
echo "   - Click 'Edit' or 'Settings'"
echo "   - Update image tag to: limpet/wizardcore-frontend:rsc-cors-fix"
echo "   - Click 'Save' and 'Redeploy'"
echo ""
echo "   Method B: SSH to Production Server"
echo "   -----------------------------------"
echo "   ssh user@your-server"
echo "   cd /path/to/wizardcore"
echo "   docker-compose pull frontend"
echo "   docker-compose up -d frontend"
echo ""
echo "   Method C: Direct Docker Commands"
echo "   ---------------------------------"
echo "   docker stop wizardcore-frontend"
echo "   docker rm wizardcore-frontend"
echo "   docker run -d \\"
echo "     --name wizardcore-frontend \\"
echo "     --network wizardcore_default \\"
echo "     -p 3001:3000 \\"
echo "     -e NEXT_PUBLIC_SUPABASE_URL=https://app.offensivewizard.com/api/auth \\"
echo "     -e NEXT_PUBLIC_SUPABASE_ANON_KEY=[your-key] \\"
echo "     -e NEXT_PUBLIC_BACKEND_URL=https://api.offensivewizard.com \\"
echo "     -e SUPABASE_INTERNAL_URL=http://supabase-auth:9999 \\"
echo "     -e GOTRUE_URL=http://supabase-auth:9999 \\"
echo "     -e BACKEND_URL=http://backend:8080 \\"
echo "     limpet/wizardcore-frontend:rsc-cors-fix"
echo ""

echo "🔍 VERIFICATION STEPS AFTER DEPLOYMENT:"
echo "---------------------------------------"
echo ""
echo "1. Clear browser cache and cookies"
echo "   - Chrome: Ctrl+Shift+Delete → 'All time' → Clear data"
echo "   - Firefox: Ctrl+Shift+Delete → 'Everything' → Clear"
echo ""
echo "2. Test login flow:"
echo "   - Go to https://app.offensivewizard.com/login"
echo "   - Log in with credentials"
echo "   - Should redirect to /dashboard (not back to login)"
echo ""
echo "3. Check browser console for errors:"
echo "   - Open DevTools (F12) → Console tab"
echo "   - Should see: '🔍 Middleware rsc-fix-20260104-1315 executing'"
echo "   - Should NOT see: 'Failed to fetch RSC payload'"
echo "   - Should NOT see: '403 Origin not allowed'"
echo ""
echo "4. Verify API calls work:"
echo "   - In Network tab, check /api/auth/auth/v1/user → should be 200"
echo "   - Check /api/backend/v1/users/me/* → should be 200"
echo ""
echo "5. Test RSC functionality:"
echo "   - Navigate between dashboard pages"
echo "   - Should load instantly (RSC working)"
echo "   - Should NOT fall back to browser navigation"
echo ""

echo "📊 WHAT THIS FIX SOLVES:"
echo "------------------------"
echo "✅ 'Guest user' issue after login"
echo "✅ 403 'Origin not allowed' errors"
echo "✅ 'Failed to fetch RSC payload' errors"
echo "✅ NS_BINDING_ABORTED errors on dashboard"
echo "✅ Infinite redirects to login page"
echo "✅ Backend API calls failing with CORS"
echo ""

echo "🛠️ TROUBLESHOOTING:"
echo "------------------"
echo ""
echo "If still having issues:"
echo ""
echo "1. Check middleware logs:"
echo "   docker logs [frontend-container] | grep -A5 -B5 'Middleware'"
echo ""
echo "2. Verify CORS fix is applied:"
echo "   docker exec [frontend-container] cat /app/app/api/auth/[...path]/route.ts | grep -A3 'function validateOrigin'"
echo "   Should show: 'if (!origin) { return \"same-origin\" }'"
echo ""
echo "3. Verify RSC detection:"
echo "   docker exec [frontend-container] cat /app/middleware.ts | grep -A2 'MIDDLEWARE_VERSION'"
echo "   Should show: 'rsc-fix-20260104-1315'"
echo ""
echo "4. Check Supabase auth cookie:"
echo "   - In browser DevTools → Application → Cookies"
echo "   - Should see 'sb-app-auth-token' cookie"
echo "   - Should NOT be expired"
echo ""
echo "5. Force restart all services:"
echo "   docker-compose down"
echo "   docker-compose up -d"
echo ""

echo "🚨 URGENT: Deploy now to fix production login and dashboard issues!"
echo ""
echo "📞 If issues persist after deployment, check:"
echo "   - Environment variables are correct"
echo "   - Supabase auth service is running"
echo "   - Backend service is healthy"
echo "   - Redis is accessible"
echo ""

echo "🎯 The fix addresses the root cause:"
echo "   - Same-origin requests without Origin headers were being rejected"
echo "   - RSC fetches were being redirected instead of returning proper errors"
echo "   - This caused the 'Failed to fetch RSC payload' and infinite redirect loop"